clone_folder: c:\projects\travis-hx

environment:
  matrix:
    - TARGET: neko
    - TARGET: cpp
    - TARGET: cs
    - TARGET: java

install:
  - echo starting
  - extra\appveyor\AppVeyor.exe setup

build_script:
  - C:\HaxeToolkit\haxe\haxe
