clone_folder: c:\projects\travis-hx

environment:
  matrix:
    - TARGET: neko
    - TARGET: cpp
    - TARGET: cs
    - TARGET: java
    - TARGET: js
    - TARGET: python
      PYTHONCMD: C:\python34\python

# matrix:
#   allow_failures:
#     - TARGET: neko
#       FILENAME: unit.n

install:
  - echo starting
  - mkdir C:\travis-hx
  - copy extra\appveyor\AppVeyor.exe C:\travis-hx
  - C:\travis-hx\AppVeyor.exe setup
  - haxelib install buddy
  - haxelib install utest

build_script:
    # expected to fail
  - cd C:\projects\travis-hx\tests\fail
  - SET HXFLAGS="-main BuddyTests -lib buddy -D reporter=buddy.reporting.TravisHxReporter"
  - C:\travis-hx\AppVeyor.exe build
  - C:\travis-hx\AppVeyor.exe test %FILENAME% && exit 1 || echo "fails as expected"
  - SET HXFLAGS="-main Utest -lib utest -D travis"
  - C:\travis-hx\AppVeyor.exe build
  - C:\travis-hx\AppVeyor.exe test %FILENAME% && exit 1 || echo "fails as expected"
    # not expected to fail
  - cd C:\projects\travis-hx\tests\success
  - SET HXFLAGS="-main BuddyTests -lib buddy -D reporter=buddy.reporting.TravisHxReporter"
  - C:\travis-hx\AppVeyor.exe build
  - C:\travis-hx\AppVeyor.exe test %FILENAME%
  - SET HXFLAGS="-main Utest -lib utest -D travis"
  - C:\travis-hx\AppVeyor.exe build
  - C:\travis-hx\AppVeyor.exe test %FILENAME%
