clone_folder: c:\projects\travis-hx

environment:
  matrix:
    # - TARGET: neko
    - TARGET: cpp
    - TARGET: cpp
      ARCH: x86_64
    - TARGET: cs
    - TARGET: cs
      ARCH: i686
    - TARGET: java
    - TARGET: java
      ARCH: i686
    - TARGET: js
    # - TARGET: python
      # PYTHONCMD: C:\python34\python

matrix:
  allow_failures:
    # buddy issue
    - TARGET: python

install:
  - echo starting
  - mkdir C:\travis-hx
  - copy extra\appveyor\AppVeyor.exe C:\travis-hx
  - C:\travis-hx\AppVeyor.exe setup
  - C:\travis-hx\AppVeyor.exe run haxelib install buddy
  - C:\travis-hx\AppVeyor.exe run haxelib install utest

build_script:
    # not expected to fail
  - cd C:\projects\travis-hx\tests\success
  - SET HXFLAGS=-main BuddyTests -lib buddy -D reporter=buddy.reporting.TravisHxReporter
  - C:\travis-hx\AppVeyor.exe build
  - C:\travis-hx\AppVeyor.exe test %FILENAME%
  - SET HXFLAGS=-main Utest -lib utest -D travis
  - C:\travis-hx\AppVeyor.exe build
  - C:\travis-hx\AppVeyor.exe test %FILENAME%
