# example appveyor.yml haxe configuration

environment:
  - HXFLAGS="-cp src -main test.TestAll"
  matrix:
    - TARGET: neko
    # optional: FILENAME
    - TARGET: interp
    - TARGET: macro
    # optional: MACROFLAGS: specify the flags that are unique to building/running with --macro arguments
    - TARGET: js
    # optional: FILENAME
    # optional: NODECMD: set the command to be run by nodejs
    - TARGET: cpp
    # optional: FILENAME
    - TARGET: cs
    # optional: FILENAME
    - TARGET: java
    # optional: FILENAME
    - TARGET: python
    # optional: FILENAME
    # optional: PYTHONCMD

matrix:
  allow_failures:
    - TARGET: cs

install: # clone travis-hx repo and setup the target
  - git clone --depth=50 --branch=master git://github.com/waneck/travis-hx.git C:\travis-hx
  - C:\travis-hx\AppVeyor.exe setup

script:
  # build the target. This will call haxe with the HXFLAGS and HXFLAGS_EXTRA environment variables
  - C:\travis-hx\AppVeyor.exe build
  # run the tests
  - C:\travis-hx\AppVeyor.exe test %FILENAME% # this will set the $FILENAME defined on the environment variable to run the tests


