clone_folder: c:\projects\travis-hx

environment:
  matrix:
    - TARGET: neko
    - TARGET: cpp
    - TARGET: cs
    - TARGET: java

install:
  - echo starting
  - extra\appveyor\AppVeyor.exe setup

build_script:
  - extra\appveyor\AppVeyor.exe retry git clone https://github.com/HaxeFoundation/haxe.git C:\haxegit
  - cd C:\haxegit\tests\unit
  - %APPVEYOR_BUILD_FOLDER%\extra\appveyor\AppVeyor.exe run haxe compile-%TARGET%.hxml -D fdb
  # - %APPVEYOR_BUILD_FOLDER%\extra\appveyor\AppVeyor.exe test
  # - extra\appveyor\AppVeyor.exe build
