clone_folder: c:\projects\travis-hx

environment:
  matrix:
    - TARGET: neko
      FILENAME: unit.n
    - TARGET: cpp
    - TARGET: cs
    - TARGET: java

matrix:
  allow_failures:
    - environment:
      TARGET: neko

install:
  - echo starting
  - mkdir C:\travis-hx
  - copy extra\appveyor\AppVeyor.exe C:\travis-hx
  - C:\travis-hx\AppVeyor.exe setup

build_script:
  - C:\travis-hx\AppVeyor.exe retry git clone https://github.com/HaxeFoundation/haxe.git C:\haxegit
  - cd C:\haxegit\tests\unit
  - C:\travis-hx\AppVeyor.exe run haxe compile-%TARGET%.hxml -D fdb
  - C:\travis-hx\AppVeyor.exe test %FILENAME%
  # - %APPVEYOR_BUILD_FOLDER%\extra\appveyor\AppVeyor.exe test
  # - extra\appveyor\AppVeyor.exe build
